---
# Ensure files directory exists
- name: Ensure files directory exists
  file:
    path: files
    state: directory
    mode: '0755'
  when: kubernetes_deployment.kubeconfig.use_remote | default(false)

# Get kubeconfig from control plane node when remote mode is enabled
- name: Get kubeconfig from control plane node
  shell: |
    ssh -i {{ kubernetes_deployment.ssh_key_path }} {{ kubernetes_deployment.default_ansible_user }}@{{ kubernetes_deployment.control_plane_nodes[0].ansible_host }} 'sudo cat {{ kubernetes_deployment.kubeconfig.remote_path | default("/etc/kubernetes/admin.conf") }}' > {{ kubernetes_deployment.kubeconfig.local_path | default("files/kubeconfig") }}
  register: kubeconfig_result
  when: kubernetes_deployment.kubeconfig.use_remote | default(false)
  
# Set proper permissions for kubeconfig
- name: Set proper permissions for kubeconfig
  file:
    path: "{{ kubernetes_deployment.kubeconfig.local_path | default('files/kubeconfig') }}"
    mode: '0600'
  when: kubernetes_deployment.kubeconfig.use_remote | default(false)

# Set global kubeconfig path based on configuration
- name: Set global kubeconfig path
  set_fact:
    global_kubeconfig: "{{ kubernetes_deployment.kubeconfig.local_path if kubernetes_deployment.kubeconfig.use_remote | default(false) else lookup('env', 'KUBECONFIG') | default(ansible_env.HOME + '/.kube/config') }}" 