---
# Configuration Validation - Validate user_input.yml for deployment type

- name: Load user_input.yml
  ansible.builtin.include_vars:
    file: user_input.yml
    name: user_config

- name: Debug configuration loading
  ansible.builtin.debug:
    msg: "Starting validation for config_type: {{ config_type | default('UNDEFINED') }}"

- name: Test direct key access
  ansible.builtin.debug:
    msg: "Direct microk8s_deployment check: {{ user_config.microk8s_deployment is defined }}"

- name: Test dynamic key access
  ansible.builtin.debug:
    msg: "Dynamic key access: {{ user_config[config_type + '_deployment'] is defined }}"

- name: Show microk8s_deployment content if it exists
  ansible.builtin.debug:
    msg: "microk8s_deployment content: {{ user_config.microk8s_deployment }}"
  when: user_config.microk8s_deployment is defined

- name: Validate deployment configuration exists
  ansible.builtin.assert:
    that:
      - config_type is defined
      - config_type != ''
      - user_config.microk8s_deployment is defined
      - user_config.microk8s_deployment.enabled is defined
    fail_msg: |
      microk8s_deployment section not found or incomplete in user_input.yml
      DEBUG: config_type={{ config_type | default('UNDEFINED') }}

- name: Check if deployment is enabled
  ansible.builtin.assert:
    that:
      - user_config[config_type + '_deployment'].enabled | bool
    fail_msg: "{{ config_type }} deployment is disabled. Set {{ config_type }}_deployment.enabled: true"

- name: Validate kubernetes_deployment section (required for node info)
  ansible.builtin.assert:
    that:
      - user_config.kubernetes_deployment is defined
      - user_config.kubernetes_deployment.control_plane_nodes is defined
      - user_config.kubernetes_deployment.control_plane_nodes | length > 0
      - user_config.kubernetes_deployment.ssh_key_path is defined
    fail_msg: "kubernetes_deployment section with node configuration is required"

- name: Set deployment facts
  ansible.builtin.set_fact:
    deployment_config: "{{ user_config[config_type + '_deployment'] }}"
    node_config: "{{ user_config.kubernetes_deployment }}"
    
- name: Display configuration summary
  ansible.builtin.debug:
    msg: |
      Configuration Summary:
      - Deployment Type: {{ config_type | upper }}
      - Enabled: {{ deployment_config.enabled }}
      - Control Plane Nodes: {{ node_config.control_plane_nodes | length }}
      - Worker Nodes: {{ node_config.get('worker_nodes', []) | length }}
      - SSH Key: {{ node_config.ssh_key_path }}
