# Kubernetes configuration
kube_version: "1.30.0"

# Etcd configuration
etcd_version: "3.5.9"  # Latest stable etcd version compatible with k8s 1.30
etcd_deployment_type: "host"

# Networking
kube_service_addresses: 10.233.0.0/18
kube_pods_subnet: 10.233.64.0/18
kube_network_plugin: calico

# Container runtime
container_manager: containerd

# DNS
dns_mode: coredns

# API Server configuration
supplementary_addresses_in_ssl_keys: 
  - "89.169.114.118"

# API Server loadbalancer (if using a load balancer)
apiserver_loadbalancer_domain_name: ""
loadbalancer_apiserver:
  address: "89.169.114.118"
  port: 6443

# Additional Kubespray configurations can be added here 