---
- name: Check if NVIDIA runtime configuration is enabled
  debug:
    msg: "NVIDIA runtime configuration is disabled. Skipping..."
  when: not kubernetes_deployment.nvidia_runtime.enabled | default(false)

# Get all nodes from the deployment configuration
- name: Combine control plane and worker nodes
  set_fact:
    k8s_nodes: "{{ kubernetes_deployment.control_plane_nodes + kubernetes_deployment.worker_nodes | default([]) }}"
  when: kubernetes_deployment.nvidia_runtime.enabled | default(false)

# Node-specific tasks that need to run on each K8s node
- name: Configure NVIDIA runtime on each node
  include_tasks: nvidia_runtime_node_config.yml
  loop: "{{ k8s_nodes }}"
  loop_control:
    loop_var: target_node
  when: kubernetes_deployment.nvidia_runtime.enabled | default(false)

# RuntimeClass tasks that only need to run once (on control plane)
- name: Configure RuntimeClass on control plane
  block:
    - name: Set kubeconfig facts
      set_fact:
        kubeconfig_path: "{{ kubernetes_deployment.kubeconfig_path | default('/etc/kubernetes/admin.conf') }}"
        kube_context: "{{ kubernetes_deployment.kube_context | default(omit) }}"

    - name: Check if kubeconfig exists
      stat:
        path: "{{ kubeconfig_path }}"
      register: kubeconfig_stat
      delegate_to: "{{ kubernetes_deployment.control_plane_nodes[0].ansible_host }}"
      vars:
        ansible_ssh_private_key_file: "{{ kubernetes_deployment.ssh_key_path }}"
        ansible_user: "{{ kubernetes_deployment.control_plane_nodes[0].ansible_user | default(kubernetes_deployment.default_ansible_user) }}"
      environment:
        LC_ALL: C.UTF-8
        LANG: C.UTF-8

    - name: Fail if kubeconfig not found
      fail:
        msg: "Kubeconfig not found at {{ kubeconfig_path }}. Ensure Kubernetes deployment completed successfully."
      when: not kubeconfig_stat.stat.exists

    - name: Check if NVIDIA RuntimeClass exists
      command: >
        kubectl --kubeconfig={{ kubeconfig_path }} get runtimeclass nvidia
      register: runtime_class_check
      failed_when: false
      changed_when: false
      delegate_to: "{{ kubernetes_deployment.control_plane_nodes[0].ansible_host }}"
      vars:
        ansible_ssh_private_key_file: "{{ kubernetes_deployment.ssh_key_path }}"
        ansible_user: "{{ kubernetes_deployment.control_plane_nodes[0].ansible_user | default(kubernetes_deployment.default_ansible_user) }}"
      environment:
        LC_ALL: C.UTF-8
        LANG: C.UTF-8

    - name: Create NVIDIA RuntimeClass manifest
      copy:
        dest: "/tmp/nvidia-runtime-class.yaml"
        content: |
          apiVersion: node.k8s.io/v1
          kind: RuntimeClass
          metadata:
            name: nvidia
          handler: nvidia
      delegate_to: "{{ kubernetes_deployment.control_plane_nodes[0].ansible_host }}"
      vars:
        ansible_ssh_private_key_file: "{{ kubernetes_deployment.ssh_key_path }}"
        ansible_user: "{{ kubernetes_deployment.control_plane_nodes[0].ansible_user | default(kubernetes_deployment.default_ansible_user) }}"
      environment:
        LC_ALL: C.UTF-8
        LANG: C.UTF-8
      when: runtime_class_check.rc != 0

    - name: Create NVIDIA RuntimeClass if not exists
      command: >
        kubectl --kubeconfig={{ kubeconfig_path }} apply -f /tmp/nvidia-runtime-class.yaml
      delegate_to: "{{ kubernetes_deployment.control_plane_nodes[0].ansible_host }}"
      vars:
        ansible_ssh_private_key_file: "{{ kubernetes_deployment.ssh_key_path }}"
        ansible_user: "{{ kubernetes_deployment.control_plane_nodes[0].ansible_user | default(kubernetes_deployment.default_ansible_user) }}"
      environment:
        LC_ALL: C.UTF-8
        LANG: C.UTF-8
      when: runtime_class_check.rc != 0

    - name: Remove temporary RuntimeClass manifest
      file:
        path: "/tmp/nvidia-runtime-class.yaml"
        state: absent
      delegate_to: "{{ kubernetes_deployment.control_plane_nodes[0].ansible_host }}"
      vars:
        ansible_ssh_private_key_file: "{{ kubernetes_deployment.ssh_key_path }}"
        ansible_user: "{{ kubernetes_deployment.control_plane_nodes[0].ansible_user | default(kubernetes_deployment.default_ansible_user) }}"
      environment:
        LC_ALL: C.UTF-8
        LANG: C.UTF-8
      when: runtime_class_check.rc != 0

    # Copy kubeconfig to local files directory
    - name: Ensure files directory exists
      file:
        path: "{{ lookup('env', 'PWD') }}/files"
        state: directory
        mode: '0755'
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
      delegate_to: localhost
      become: true

    - name: Copy kubeconfig from control plane to local files directory
      fetch:
        src: "{{ kubeconfig_path }}"
        dest: "{{ lookup('env', 'PWD') }}/files/kubeconfig"
        flat: yes
      delegate_to: "{{ kubernetes_deployment.control_plane_nodes[0].ansible_host }}"
      vars:
        ansible_ssh_private_key_file: "{{ kubernetes_deployment.ssh_key_path }}"
        ansible_user: "{{ kubernetes_deployment.control_plane_nodes[0].ansible_user | default(kubernetes_deployment.default_ansible_user) }}"
      environment:
        LC_ALL: C.UTF-8
        LANG: C.UTF-8

    - name: Set kubeconfig permissions and ownership
      file:
        path: "{{ lookup('env', 'PWD') }}/files/kubeconfig"
        mode: '0644'
        owner: "{{ lookup('env', 'USER') }}"
        group: "{{ lookup('env', 'USER') }}"
      become: true
      ignore_errors: true

    - name: Ensure kubeconfig is readable
      file:
        path: "{{ lookup('env', 'PWD') }}/files/kubeconfig"
        mode: '0644'
      become: true
      ignore_errors: true

  when: kubernetes_deployment.nvidia_runtime.enabled | default(false)

- name: Display completion message
  debug:
    msg: "NVIDIA runtime configuration completed successfully on all nodes"
  when: kubernetes_deployment.nvidia_runtime.enabled | default(false) 