---
galaxy_info:
  author: k3s-automation
  description: Automatically detect Jetson devices and install jetson-stats for monitoring
  company: k3s-automation
  license: Apache-2.0
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
  galaxy_tags:
    - jetson
    - nvidia
    - tegra
    - monitoring
    - system
    - prerequisites
    - jetson-stats
    - jtop

dependencies: []
