{
 "title": "nim-dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Throughput (tok/sec)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(generation_tokens_total{namespace=\"nim\", pod=~'meta-llama3-8b-instruct-.*'}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Tokens Over Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(generation_tokens_total{namespace=\"nim\", pod=~'meta-llama3-8b-instruct-.*'}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Num Requests Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(num_requests_running) by (model_name) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{condition=\"true\", namespace=\"nim\", pod=~'meta-llama3-8b-instruct-.*',kubernetes_node='demo-1'})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Smartscaler Recommendations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "smartscaler_hpa_num_pods{job=\"pushgateway\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Generated Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(request_generation_tokens_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(request_generation_tokens_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(request_generation_tokens_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "Num Request Waiting",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by(job) (num_requests_waiting)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inter Token Latency (ITL)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(time_per_output_token_seconds_bucket[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Total Requests Over Time",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(request_success_total[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Context vs Generated Tokens",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 15, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "prompt_tokens_total", "legendFormat": "Context Tokens" },
    { "expr": "generation_tokens_total", "legendFormat": "Generated Tokens" }
   ]
  },
  {
   "title": "Requests Waiting",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_requests_waiting", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "num_requests_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Req per second",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(rate(request_success_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time to First Token (TTFT)",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "rate(time_to_first_token_seconds_bucket[$__rate_interval])",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Time to First Token (TTFT) p50",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(time_to_first_token_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inter-Token Latency (ITL) p50",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(time_per_output_token_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "percent under 30s",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "sum(e2e_request_latency_seconds_bucket{le=\"30.0\"}) by (pod)/sum(e2e_request_latency_seconds_bucket{le=\"60.0\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prompt Tokens",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(request_prompt_tokens_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(request_prompt_tokens_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(request_prompt_tokens_bucket[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "K/V Cache Utilization",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gpu_cache_usage_perc{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 64 },
   "targets": [
    {
     "expr": "rate(request_success_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "E2E Req Latency sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "rate(e2e_request_latency_seconds_sum[1m]) / rate(e2e_request_latency_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}